name: Docker build and push

on: 
  push:
    branches: [ v3 ]
  pull_request:
    branches: [ v3 ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: keepsobp
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to GitHub registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: keepsobp/hikari:v3